[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seantral-data-pipeline"
version = "0.0.1"
description = "Data ingestion and processing pipeline for Seantral"
readme = "README.md"
authors = [
    {name = "Seantral Team"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "duckdb>=0.9.0",
    "fastapi>=0.100.0",
    "pydantic>=2.0.0",
    "pytest>=7.0.0",
    "pyarrow>=14.0.0",
    "boto3>=1.28.0",
    "httpx>=0.24.0",
    "loguru>=0.7.0",
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mypy",
    "pytest-cov",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.ruff]
target-version = "py312"
line-length = 100
select = ["E", "F", "B", "I"]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true 