name: CI API

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "packages/data-pipeline/**"
      - ".github/workflows/ci-api.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/api/**"
      - "packages/data-pipeline/**"
      - ".github/workflows/ci-api.yml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest pytest-cov
          pip install -r apps/api/requirements.txt

      - name: Lint with ruff
        run: |
          ruff check apps/api
          ruff check packages/data-pipeline

      - name: Format check with black
        run: |
          black --check apps/api
          black --check packages/data-pipeline

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r apps/api/requirements.txt
          pip install -e packages/data-pipeline

      - name: Test with pytest
        run: |
          cd apps/api && pytest --cov=. --cov-report=xml
          cd ../../packages/data-pipeline && pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./apps/api/coverage.xml,./packages/data-pipeline/coverage.xml
          flags: api,data-pipeline
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

  # TODO: Add build and deployment job for Railway or AWS Fargate 